application: bsuirsched
version: 2-0-test
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: "7d"
- url: /static
  static_dir: static
  expiration: "100d"
- url: /admin.*
  script: admin.app
  login: admin
- url: /tasks/.*
  script: tasks.app
  login: admin
- url: .*
  script: myapp.app
libraries:
- name: lxml
  version: latest
- name: django
  version: latest